version: "3.9"
services:
  books-backend-mysql:
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: Books
      MYSQL_USER: booksbackend
      MYSQL_PASSWORD: booksBackend!
      MYSQL_ROOT_PASSWORD: admin12345!